version: '3.8'
services:
  app1:
    build: .
    environment:
      - APP_NAME= NGINX1
    ports:
      - "3001:3000"

  app2:
    build: .
    environment:
      - APP_NAME=nginx2
    ports:
      - "30002:3000"